InputHandler::InputHandler(WebPagePrivate* page)
    : m_webPage(page)
    , m_currentFocusElement(0)
    , m_inputModeEnabled(false)
    , m_processingChange(false)
    , m_shouldEnsureFocusTextElementVisibleOnSelectionChanged(false)
    , m_currentFocusElementType(TextEdit)
    , m_currentFocusElementTextEditMask(DEFAULT_STYLE)
    , m_composingTextStart(0)
    , m_composingTextEnd(0)
    , m_pendingKeyboardVisibilityChange(NoChange)
    , m_delayKeyboardVisibilityChange(false)
    , m_request(0)
    , m_processingTransactionId(-1)
    , m_receivedBackspaceKeyDown(false)
    , m_expectedKeyUpChar(0)
    , m_didSpellCheckWord(false)
{
}
